kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: argo-cd
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'argo-cd:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: {{ .Values.source_url }}
      ref: {{ .Values.ref }}
    contextDir: /
  triggers:
    - type: ConfigChange
  runPolicy: Serial