kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: argoproj
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: build
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'argoproj:master'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: {{ .Values.source_url }}
      ref: {{ .Values.ref }}
  triggers:
    - type: ConfigChange
  runPolicy: Serial
