kind: Secret
apiVersion: v1
metadata:
  name: cluster-kubernetes.default
  labels:
    argocd.argoproj.io/secret-type: cluster
  annotations:
    managed-by: argocd.argoproj.io
data:
  config: eyJ0bHNDbGllbnRDb25maWciOnsiaW5zZWN1cmUiOmZhbHNlfX0=
  name: aW4tY2x1c3Rlcg==
  namespaces: {{ .Release.Namespace | b64enc }}
  server: aHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3Zj
type: Opaque
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2021-10-20T19:30:56Z"
  name: do-it-all
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-do-it-all
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: do-it-all
subjects:
- kind: ServiceAccount
  name: argocd-application-controller


  